language: android

jdk:
  - oraclejdk8

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.0
  - echo y | android update sdk -u -a -t android-26
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

script:
  - ./gradlew clean assembleDebug check

sudo: false